//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int IDFile { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        public int PetIDPet { get; set; }
    
        public virtual Pets Pets { get; set; }
    }
}
